### ISSUE TITLE
Error compiling and testing

### ISSUE THREAD

**Issue by Axel07l** [MQuaresma/pswoosh#1]
Hi, 
I just try to compile your code and I have to change every `skey_deriv` to `pswoosh_skey_deriv` to be able to compile properly.

Also When I run the test. It's all pass except `test_scheme`

`thread 'tests::test_scheme' has overflowed its stack`
`fatal runtime error: stack overflow `

thanks

**Comment by MQuaresma** [comment]
Hi,

Thanks for pointing this out, it has been fixed in 2f67a2d260961c865eea5b168cc410c15f869940.

As for the tests, this has to do with the default stack space allocated by Rust runtime, which
isn't enough to store the matrix which is allocated in the stack.
For the tests to go through the `RUST_MIN_STACK` env variable needs to be set appropriately as such: `RUST_MIN_STACK=1048576000`.
